In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from prettytable import PrettyTable

In [2]:
# 1) Таблица умножения
table = PrettyTable()
numbers = np.arange(1, 11)
table.field_names = ["\\"] + [str(n) for n in numbers]
for vertical_num in numbers:
    table.add_row(
        [vertical_num] + [vertical_num * horizontal_num for horizontal_num in numbers])
print(table)


+----+----+----+----+----+----+----+----+----+----+-----+
| \  | 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  |  10 |
+----+----+----+----+----+----+----+----+----+----+-----+
| 1  | 1  | 2  | 3  | 4  | 5  | 6  | 7  | 8  | 9  |  10 |
| 2  | 2  | 4  | 6  | 8  | 10 | 12 | 14 | 16 | 18 |  20 |
| 3  | 3  | 6  | 9  | 12 | 15 | 18 | 21 | 24 | 27 |  30 |
| 4  | 4  | 8  | 12 | 16 | 20 | 24 | 28 | 32 | 36 |  40 |
| 5  | 5  | 10 | 15 | 20 | 25 | 30 | 35 | 40 | 45 |  50 |
| 6  | 6  | 12 | 18 | 24 | 30 | 36 | 42 | 48 | 54 |  60 |
| 7  | 7  | 14 | 21 | 28 | 35 | 42 | 49 | 56 | 63 |  70 |
| 8  | 8  | 16 | 24 | 32 | 40 | 48 | 56 | 64 | 72 |  80 |
| 9  | 9  | 18 | 27 | 36 | 45 | 54 | 63 | 72 | 81 |  90 |
| 10 | 10 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 |
+----+----+----+----+----+----+----+----+----+----+-----+


In [3]:
# 2) Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число),
# и разность (вещественное число) и создает матрицу numpy по диагонали, которой располагаются первые N членов
# арифметической прогрессии.
def arithmetic_progression(n: int, first_el: float, step: float):
    matrix = np.zeros((n, n))
    for i in range()
        

    print(matrix)

foo(5, 0)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
